// getAllItems
export const GET_ALL_ITEMS_REQUEST = 'GET_ALL_ITEMS_REQUEST'
export const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS'
export const GET_ALL_ITEMS_FAILURE = 'GET_ALL_ITEMS_FAILURE'
// createItem
export const ADD_EMPTY_ITEM = 'ADD_EMPTY_ITEM'
export const CREATE_ITEM_REQUEST = 'CREATE_ITEM_REQUEST'
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS'
export const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE'
// updateItem
export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST'
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS'
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE'
// deleteItem
export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE'
// completeItem
export const COMPLETE_ITEM_REQUEST = 'COMPLETE_ITEM_REQUEST'
export const COMPLETE_ITEM_SUCCESS = 'COMPLETE_ITEM_SUCCESS'
export const COMPLETE_ITEM_FAILURE = 'COMPLETE_ITEM_FAILURE'
// uncompleteItem
export const UNCOMPLETE_ITEM_REQUEST = 'UNCOMPLETE_ITEM_REQUEST'
export const UNCOMPLETE_ITEM_SUCCESS = 'UNCOMPLETE_ITEM_SUCCESS'
export const UNCOMPLETE_ITEM_FAILURE = 'UNCOMPLETE_ITEM_FAILURE'
